### ISSUE TITLE
Vulkan app take more and more RAM over time

### ISSUE THREAD

**Issue by Arttys1** [KyleMayes/vulkanalia#104]
Hello,

First of all, thank you for your amazing work on these bindings and this tutorial.
Let me explain my problem. After finish your tuto, i continue to develop my app on my side until i saw that my application eat a lot of RAM and it grows over the time. At the beginning, i thought that i have make a mistake somewhere but i was unable to find it. So i decided to run the code of the last chapter of your tuto and i see that it has the same problem.
I don't know if i did something wrong (like in the config or whatever). If you have some idea i would be delighted.

Thank you for your time,
Arttys.

**Comment by KyleMayes** [comment]
Thanks for the report, I was able to replicate the memory leak.

I think I see what is going wrong, it seems I shouldn't be reallocating command buffers every frame, resetting command pools resets command buffers but it doesn't deallocate them.

I should have an update for the tutorial out soon.

**Comment by KyleMayes** [comment]
I'm considering rewriting the last chapter on secondary command buffers after discovering my misunderstanding of how resetting command pools works. In the meantime, here is an update to the next-to-last chapter which you can look at to see what you need to change: https://github.com/KyleMayes/vulkanalia/commit/911b394f2f68362bbe2ca3e3442f1c268ce572f5

Basically don't reallocate the command buffers every frame, just reuse them directly when resetting the command pool. Not sure how I screwed up this badly, but that is why the last few chapters have the disclaimer... 😅

**Comment by Arttys1** [comment]
Thank you very much for your fast reply. I will try to fix that.
Your two last chapters allow me a better understanding of how to use vulkan so thank you :D

**Comment by KyleMayes** [comment]
Ended up not requiring as many changes as I thought, I've fixed the leaks in that PR.
Please let me know if you run into any more problems, thanks.
