### ISSUE TITLE
Can't find how to enable enumeration portability

### ISSUE THREAD

**Issue by Legellon** [KyleMayes/vulkanalia#111]
I use MacBook Pro 2015 while following the tutorial and can't successfully run the code from the Setup/Instance section.

> Error: The requested version of Vulkan isn't supported by the driver or is otherwise incompatible for implementation-specific reasons.

As far as I know (I'm quite a newbie to Vulkan btw) this may occur even on systems which could have support for Vulkan over some other API(in my case over MoltenVK, I guess) because the layer around enumeration portability is turned off by default.

I launched a simple triangle example(https://github.com/vulkano-rs/vulkano/blob/master/examples/src/bin/triangle.rs) of the Vulkano wrapper with the following instance setup and everything works just fine.

```rust
let library = VulkanLibrary::new().unwrap();
let required_extensions = vulkano_win::required_extensions(&library);

// Now creating the instance.
let instance = Instance::new(
    library,
    InstanceCreateInfo {
        enabled_extensions: required_extensions,
        // Enable enumerating devices that use non-conformant vulkan implementations. (ex. MoltenVK)
        enumerate_portability: true,
        ..Default::default()
    },
)
.unwrap();
```

I think that a solution is just to enable somehow this layer in Vulkanalia, but I can't find how exactly I should make it.

**Comment by KyleMayes** [comment]
I haven't seen this before, but I've done very limited testing on macOS and don't currently have access to a macOS device.

I will look into this more later, but for now:

This library does have the `KHR_PORTABILITY_SUBSET_EXTENSION` extension: 
https://github.com/KyleMayes/vulkanalia/blob/7e0a012533757a3662583a46d0c47a8a2cc5903e/vulkanalia-sys/src/extensions.rs#L3412

However, this is a "provisional" extension meaning it is not stable.
You will need to enable the `provisional` Cargo feature on this crate to access it.

Then you can add the name of the extension to the list of extensions passed to the instance creation info.
For example, here is the relevant line from the tutorial:
https://github.com/KyleMayes/vulkanalia/blob/7e0a012533757a3662583a46d0c47a8a2cc5903e/tutorial/src/01_instance_creation.rs#L93

**Comment by Legellon** [comment]
I have added an extension, but the same error still appears. And I have added the provisional feature, of course.

```rust
unsafe fn create_instance(window: &Window, entry: &Entry) -> Result<Instance> {
    let application_info = vk::ApplicationInfo::builder()
        .application_name(b"Vulkan Tutorial\0")
        .application_version(vk::make_version(1, 0, 0))
        .engine_name(b"No Engine\0")
        .engine_version(vk::make_version(1, 0, 0))
        .api_version(vk::make_version(1, 0, 0));

    let mut extensions: Vec<_> = vk_window::get_required_instance_extensions(window)
        .iter()
        .map(|e| e.as_ptr())
        .collect();

    // !!
    extensions.push(KHR_PORTABILITY_ENUMERATION_EXTENSION.name.as_ptr());

    let info = vk::InstanceCreateInfo::builder()
        .application_info(&application_info)
        .enabled_extension_names(&extensions);

    Ok(entry.create_instance(&info, None)?)
}
```

Do I use extensions in the wrong way?

**Comment by KyleMayes** [comment]
That code looks correct, I will try to look more into this over the weekend.
Perhaps `enumerate_portability` is doing more work in `vulkano`.

**Comment by wolkenmachine** [comment]
I'm running into the same issue. According to [this page](https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Instance#page_Encountered-VK_ERROR_INCOMPATIBLE_DRIVER) we must also set `VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR` when using MoltenVK:


> Beginning with the 1.3.216 Vulkan SDK, the VK_KHR_PORTABILITY_subset extension is mandatory.
> To get over this error, first add the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR bit to [VkInstanceCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkInstanceCreateInfo.html) struct's flags, then add VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME to instance enabled extension list.

**Comment by zgljl2012** [comment]
I add `extensions.push(KHR_PORTABILITY_ENUMERATION_EXTENSION.name.as_array() as *const i8);` and `.flags(InstanceCreateFlags::ENUMERATE_PORTABILITY_KHR)` just like @wolkenmachine said, it works:

```rust
unsafe fn create_instance(window: &Window, entry: &Entry) -> Result<Instance> {
    let application_info = vk::ApplicationInfo::builder()
        .application_name(b"Vulkan Tutorial\0")
        .application_version(vk::make_version(1, 0, 0))
        .engine_name(b"No Engine\0")
        .engine_version(vk::make_version(1, 0, 0))
        .api_version(vk::make_version(1, 0, 0));
    let mut extensions = vk_window::get_required_instance_extensions(window)
        .iter()
        .map(|e| e.as_ptr())
        .collect::<Vec<_>>();
    extensions.push(KHR_PORTABILITY_ENUMERATION_EXTENSION.name.as_array() as *const i8);
    let info = vk::InstanceCreateInfo::builder()
        .application_info(&application_info)
        .flags(InstanceCreateFlags::ENUMERATE_PORTABILITY_KHR)
        .enabled_extension_names(&extensions);
    
   Ok(entry.create_instance(&info, None)?)
}

```
