### ISSUE TITLE
syntax error in 23_texture_image.rs and onward

### ISSUE THREAD

**Issue by handwovenwrinkle** [KyleMayes/vulkanalia#113]
At line 928 in `24_sampler.rs`, `let (info, mut reader) = decoder.read_info()?;` causes a syntax error of `expected struct 'Reader', found tuple`.

**Comment by handwovenwrinkle** [comment]
This seems to be caused by the latest version of the `png` crate.
Though I'd consider this a band-aid fix, as I like to keep dependencies up to date.

**Comment by KyleMayes** [comment]
I've updated the dependencies for the tutorial.
