### ISSUE TITLE
Issue with 27_model_loading.rs on MacOS

### ISSUE THREAD

**Issue by Tony-Klink** [KyleMayes/vulkanalia#118]
When running this tutorial final image look like this:
<img width="1136" alt="Screenshot 2022-11-23 at 16 18 06" src="https://user-images.githubusercontent.com/1422270/203655512-15b16de0-29d4-41a7-a030-7398cf821f06.png">

**Comment by KyleMayes** [comment]
Could you provide some more information?
Are you running the sample code or your own code?
What chapter is this from?

**Comment by Tony-Klink** [comment]
Sorry, It was my issue. Thank you for Great Tutorial!
