### ISSUE TITLE
Error of tutorial 2 - Instance on macOS with vulkan version 1.3.236

### ISSUE THREAD

**Issue by wutianyuan1** [KyleMayes/vulkanalia#121]
When I run the code of tutorial 2 - Instance on my Mac, the following error occurs.
```
(GENERAL) vkCreateInstance: Found drivers that contain devices which support the portability subset, but the portability enumeration bit was not set! Applications that wish to enumerate portability drivers must set the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR bit in the VkInstanceCreateInfo flags and enable the VK_KHR_portability_enumeration instance extension.
```
This may due to the latest vulkan on macOS requires to explicitly enable the KHR_PORTABILITY_ENUMERATION_EXTENSION feature, so maybe we should add this line when building the extensions.
```rust
extensions.push(vk::KHR_PORTABILITY_ENUMERATION_EXTENSION.name.as_ptr());
```

**Comment by KyleMayes** [comment]
I updated the tutorial and the code samples to enable this extension when it is supported.
