### ISSUE TITLE
(Tutorial) Further macOS compatibility: `VK_KHR_portability_subset` and `VK_KHR_get_physical_device_properties2` extensions

### ISSUE THREAD

**Issue by bm-w** [KyleMayes/vulkanalia#129]
_Note: LunarG Vulkan SDK 1.3.236.0, macOS Ventura 13.1, Apple M1 Max_

During [chapter 9 of the tutorial, “Logical device and queues”](https://kylemayes.github.io/vulkanalia/setup/logical_device_and_queues.html), I encounter the following validation error during logical device creation (newlines added for clarity):
```
(VALIDATION) Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ]
Object 0: handle = 0x600000d71fc0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 |
vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x600000d71fc0[] supports it The Vulkan spec states: If the VK_KHR_portability_subset extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensionNames must include "VK_KHR_portability_subset"
(https://vulkan.lunarg.com/doc/view/1.3.236.0/mac/1.3-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)
```

This can be handled by checking whether [`VK_KHR_portability_subset`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_portability_subset.html) is indeed included in the physical device’s properties, and if so enabling the corresponding extension for the logical device in [`create_logical_device`](https://github.com/KyleMayes/vulkanalia/blob/d51ce3dc/tutorial/src/04_logical_device.rs#L255):
```
unsafe fn create_logical_device(instance: &Instance, data: &mut AppData) -> Result<Device> {
    // ...

    let features = vk::PhysicalDeviceFeatures::builder();

    // Extensions

    let extensions = if instance
        .enumerate_device_extension_properties(data.physical_device, None)?
        .iter()
        .any(|p| p.extension_name == vk::KHR_PORTABILITY_SUBSET_EXTENSION.name)
    {
        vec![vk::KHR_PORTABILITY_SUBSET_EXTENSION.name.as_ptr()]
    } else {
        vec![]
    };

    // Create

    let queue_infos = &[queue_info];
    let info = vk::DeviceCreateInfo::builder()
        // ...
        .enabled_features(&features)
        .enabled_extension_names(&extensions);

    // ...
}
```

---

The above indeed avoids the aforementioned validation error, but in its turn introduces a new one (newlines added for clarity):
```
(VALIDATION) Validation Error: [ VUID-vkCreateDevice-ppEnabledExtensionNames-01387 ]
Object 0: handle = 0x12f014c00, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x12537a2c |
Missing extension required by the device extension VK_KHR_portability_subset: VK_KHR_get_physical_device_properties2. The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list
(https://vulkan.lunarg.com/doc/view/1.3.236.0/mac/1.3-extensions/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)
```

This can be handled by enabling the [`VK_KHR_get_physical_device_properties2`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_get_physical_device_properties2.html) instance extension in [`create_instance`](https://github.com/KyleMayes/vulkanalia/blob/d51ce3dc/tutorial/src/04_logical_device.rs#L117):
```
unsafe fn create_instance(window: &Window, entry: &Entry, data: &mut AppData) -> Result<Instance> {
    // ...

    // Required by Vulkan SDK on macOS since 1.3.216.
    let flags = if entry
        .enumerate_instance_extension_properties(None)?
        .iter()
        .any(|e| e.extension_name == vk::KHR_PORTABILITY_ENUMERATION_EXTENSION.name)
    {
        extensions.push(vk::KHR_PORTABILITY_ENUMERATION_EXTENSION.name.as_ptr());
        extensions.push(vk::KHR_GET_PHYSICAL_DEVICE_PROPERTIES2_EXTENSION.name.as_ptr());
        vk::InstanceCreateFlags::ENUMERATE_PORTABILITY_KHR
    } else {
        vk::InstanceCreateFlags::empty()
    };

    // ...
}
```

Since this extension needs to be enabled for the instance, during its creation, I’m not sure if there is an elegant way to check whether it is actually needed. We can’t check yet whether `VK_KHR_portability_subset` is included in the physical device properties, as that requires the instance to have already been created and the physical device to have already been picked.

In the snippet above I’m enabling `VK_KHR_get_physical_device_properties2` if we’re also enabling [`VK_KHR_portability_enumeration`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_portability_enumeration.html). IIUC this can still lead to a situation where it is enabled unnecessarily. I can’t tell from reading [its documentation](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_get_physical_device_properties2.html) or the wider internet whether that might somehow affect other devices / platforms.

---

Enabling these two extensions, I got through the rest of the tutorial (through chapter 34, at least — that’s how far I’ve gotten so far) without further macOS-related validation errors.

**Comment by KyleMayes** [comment]
I recently came into possession of shiny new M2 MacBook Air so I was finally able to properly work on this.

I've just pushed changes to the example and the tutorial that enable the `VK_KHR_get_physical_device_properties2` instance extension and the `VK_KHR_portability_subset` device extension when compiling for macOS and the Vulkan SDK version is 1.3.216 or later.
