### ISSUE TITLE
How do I statically link the Vulkan library into my binary? 

### ISSUE THREAD

**Issue by bkolligs** [KyleMayes/vulkanalia#131]
Curious if this is possible with `vulkanalia`. Thanks!

**Comment by KyleMayes** [comment]
I'm not very familiar with the packaging of Vulkan applications, but I believe the idea is that on most platforms the Vulkan drivers will be available as part of whatever graphics drivers the user has installed for their Vulkan-compatible device.

The big exception here is macOS where Vulkan is implemented as a layer over Metal. The MoltenVK guide has information on how to package Vulkan applications for macOS: https://github.com/KhronosGroup/MoltenVK/blob/main/Docs/MoltenVK_Runtime_UserGuide.md#install
