### ISSUE TITLE
get_require_instance_extension is incompatible with versions of winit beyond "0.27.5"

### ISSUE THREAD

**Issue by LouChiSoft** [KyleMayes/vulkanalia#132]
While following the tutorial series, I noted that if you try to update to the latest version, which as of right now is `0.28.1`, you are unable to use `vulkanalia::window::get_rquired_instance_extensions()`. The error states it's because `winit::Window` doesn't implement `HasRawWindowHandle`. When I looked it up it appears that the winit devs have changed how you get a raw handle from their windows. 

Not the end of the world, but would be nice if we could use the updated versions of winit. Cheers

**Comment by KyleMayes** [comment]
I've just pushed changes to the tutorial that uses `winit` 0.28 with the split window traits.
