### ISSUE TITLE
Possible code error in vulkanalia/tutorial/book/src/presentation/swapchain.md 

### ISSUE THREAD

**Issue by kittivelae** [KyleMayes/vulkanalia#142]
Hi,

I was doing the Presentation - Swapchain chapter of the tutorial and I got to this part that starts from line 23 in the .md file:

Next, create a new function `check_physical_device_extensions` that is called from `check_physical_device` as an additional check:

```
unsafe fn check_physical_device(
    instance: &Instance,
    data: &AppData,
    physical_device: vk::PhysicalDevice,
) -> Result<()> {
    QueueFamilyIndices::get(instance, data, physical_device)?;
    check_physical_device_extensions(instance, physical_device)?;
    Ok(extensions)
}

// ...more code down here
```

Now, there is no variable `extensions` in scope and when the function was first written earlier in the tutorial returns `Ok(())`. I also compared it to the final code for the chapter located in tutorial/src/06_swapchain_creation.rs and that one also returns `Ok(())`. So it seems there is a mistake with the code in the .md file?

I'd just put in a PR for it but I am new to Rust and I am concerned that I have missed something rather than there being a mistake in the book.

**Comment by KyleMayes** [comment]
Your diagnosis was correct, I've fixed this in the tutorial.
Thanks!
