### ISSUE TITLE
Unspecified change to asset in tutorial

### ISSUE THREAD

**Issue by h0shin** [KyleMayes/vulkanalia#147]
Currently it is specified that `viking_room.obj` is modified but not `viking_room.png`.

As the original format is RGB, not RGBA, this leads to the texture data being the wrong size compared
to the expected image size, which leads to validation errors as well as simply broken textures.

I spent an embarrassing amount of time figuring out why the kept failing on my laptop before remembering I'd downloaded the C++ vulkan-tutorial assets on there, and comparing them with the ones from this tutorial.

Could be good to either specify more clearly that this tutorial uses different assets than the original, or add a check for that organically in the tutorial. Maybe by deriving the format from the color_type and checking that it matches what we expect. But I guess the point is to keep things simple...

Anyway, just putting it out there. I don't suppose most people download the assets from somewhere else.

**Comment by KyleMayes** [comment]
I didn't even realize there were changes.

I've made the following changes:

1. Added a note to the tutorial text to say there may be differences between the original files, the files from the original C++ tutorial, and the files included in this tutorial
2. Added verification code (for width, height, and color type) to the tutorial and the sample code as an extra line of defense
