### ISSUE TITLE
Question about fps of the example

### ISSUE THREAD

**Issue by Latias94** [KyleMayes/vulkanalia#148]
Thanks for your Vulkan tutorial in rust, here is a question.
I run your triangle example in release mode and my implementation with ash, their frame rate are nearly 4000+ fps on my pc.  
Then I run [SaschaWillems/Vulkan](https://github.com/SaschaWillems/Vulkan) 's triangle demo, it has 8000+fps in debug mode and 10000+fps in release mode.
I'm just curious about why there is the major difference. like event handling? or the way of frame in flight?
It is clearly not a bug, I just wondering which part will produce such a different.

**Comment by KyleMayes** [comment]
I'm not sure, but a potential culprit is the debug layer.

My triangle example and the `ash` triangle example both enable the Vulkan debug layer but it looks like the SashaWillems triangle example [doesn't by default](https://github.com/SaschaWillems/Vulkan/blob/master/examples/triangle/triangle.cpp#L31). 

I'm not sure how much overhead the debug layer adds, but for a trivial program like a triangle example, it might be significant enough to cause such a significant difference. You might try running the SashaWillems triangle example with the debug layer enabled and see what difference that makes.

**Comment by Latias94** [comment]
I release build all the examples and use renderdoc to get fps. I do know renderdoc will decrease application during profiling, so I screenshot the result of them with renderdoc profiling.

![image](https://user-images.githubusercontent.com/13315417/235178076-a90fb0b8-1063-4096-a362-ec6ed7e6babe.png)

Vulkan Examples' triangle prebuild the commands and reuse them each frame. However I don't think that is the main reason.
