### ISSUE TITLE
Command wrappers that take a slice of create info structs only return a single result

### ISSUE THREAD

**Issue by EllarBooher** [KyleMayes/vulkanalia#161]
As far as I can see, for every generated method in `extensions.rs` that takes a `create_infos` slice as a parameter: the return value is a single value instead of a vector. This blocks access to the other values the driver creates, and probably leads to out of bounds memory accesses. Some examples below:
https://github.com/KyleMayes/vulkanalia/blob/d35626650501abca8d6d472b4fef0f512e525b04/vulkanalia/src/vk/extensions.rs#L6663-L6683
https://github.com/KyleMayes/vulkanalia/blob/d35626650501abca8d6d472b4fef0f512e525b04/vulkanalia/src/vk/extensions.rs#L8366-L8390
I'm not sure what the full scope of the issue is, since methods like `get_calibrated_timestamps_ext` return a vector fine despite taking an info slice.
I'd like to contribute a PR myself, but I'm not familiar with Kotlin nor code generation. I'll take a crack at it soon, but I have no idea if I'll figure something out.

**Comment by KyleMayes** [comment]
I'm taking a look at this.

**Comment by KyleMayes** [comment]
Thanks for the report!

Not sure how I missed this one, I thought this just affected some extension methods like the examples you provided, but it even affected `create_graphics_pipelines` which is used in the example!

I've released `v0.20.0` with this fix.

**Comment by EllarBooher** [comment]
Thanks for the quick turnaround. Yeah, I was pretty surprised when I saw the issue. I only found it because the spec has only a plural method for creating raytracing pipelines, which I'm using now.
