### ISSUE TITLE
Validation Error running Chapter 7's project

### ISSUE THREAD

**Issue by Fletterio** [KyleMayes/vulkanalia#168]
This happens when trying to run the project when main.rs is identical to the one in https://github.com/KyleMayes/vulkanalia/blob/master/tutorial/src/02_validation_layers.rs :

![image](https://github.com/KyleMayes/vulkanalia/assets/40742817/609fe94a-459e-48d4-81bb-8b825f4481db)

**Comment by Fletterio** [comment]
So I went to the line that sets the vk::DebugUtilsMessageTypeFlagsEXT::all() bitset and replaced it with vk::DebugUtilsMessageTypeFlagsEXT::from_bits_unchecked(x). It fails for x = 8 which corresponds to the DEVICE_ADDRESS_BINDING flag

**Comment by KyleMayes** [comment]
I think this is caused when using `::all()` for a set of flags and that set of flags contains flags that were introduced by a newer version of Vulkan than the application is using. If you upgrade the version of Vulkan you are using, this warning should go away.

Perhaps either `::all()` should be avoided in the tutorial or maybe at least a warning should be added about this possibility.

**Comment by KyleMayes** [comment]
I added a note about the possibility of this message to the tutorial.

**Comment by Fletterio** [comment]
What's weird is I'm supposed to have the latest SDK version, I'll check again once I'm back home
