### ISSUE TITLE
PhysicalDeviceFeatures2 next reset to null after create_device?

### ISSUE THREAD

**Issue by dsvensson** [KyleMayes/vulkanalia#188]
Trying to enable indexing features like this, but after the `create_device` call, `features2.next` is `NULL` and the validation layer complains on my later use of the features it's supposed to enable, so it feels like it's somehow being set to `NULL` behind the Rust wrappers and before passed to the Vulkan APIs, and thus isn't enabled. Any ideas?

```rust
    let mut indexing_features = vk::PhysicalDeviceDescriptorIndexingFeaturesEXT::default();

    let mut features2 = vk::PhysicalDeviceFeatures2::builder()
        .push_next(&mut indexing_features)
        .build();

    instance.get_physical_device_features2(data.physical_device, &mut features2);

    let info = vk::DeviceCreateInfo::builder()
        .queue_create_infos(&queue_infos)
        .enabled_layer_names(&layers)
        .enabled_extension_names(&extensions)
        .push_next(&mut features2)
        .build();

    let device = instance.create_device(data.physical_device, &info, None)?;
```

If I print features after the call to `create_device` I can see that `features2.next` is `NULL`, but otherwise the fields look good. All settings in both `features2` and `indexing_features` are enabled, so feels like the Vulkan API never gets to see the `indexing_features`.

Validation errors that follow:
```
 ERROR vk > (VALIDATION) Validation Error: [ VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingSampledImageUpdateAfterBind-03006 ] Object 0: handle = 0x2737212bd70, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd0b29e14 | vkCreateDescriptorSetLayout(): pBindings[0] can't have VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT for VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER since descriptorBindingSampledImageUpdateAfterBind is not enabled. The Vulkan spec states: If VkPhysicalDeviceDescriptorIndexingFeatures::descriptorBindingSampledImageUpdateAfterBind is not enabled, all bindings with descriptor type VK_DESCRIPTOR_TYPE_SAMPLER, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, or VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE must not use VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT (https://vulkan.lunarg.com/doc/view/1.3.243.0/windows/1.3-extensions/vkspec.html#VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingSampledImageUpdateAfterBind-03006)
 ERROR vk > (VALIDATION) Validation Error: [ VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingPartiallyBound-03013 ] Object 0: handle = 0x2737212bd70, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x95331f1c | vkCreateDescriptorSetLayout(): pBindings[0] can't have VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT for VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER since descriptorBindingPartiallyBound is not enabled. The Vulkan spec states: If VkPhysicalDeviceDescriptorIndexingFeatures::descriptorBindingPartiallyBound is not enabled, all elements of pBindingFlags must not include VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT (https://vulkan.lunarg.com/doc/view/1.3.243.0/windows/1.3-extensions/vkspec.html#VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-descriptorBindingPartiallyBound-03013)
```

When inspecting the device in NSight Graphics, I can see that `pNext` of `VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2` is set to `NULL`.

Could it be some weird lifetime issue?

**Comment by dsvensson** [comment]
Before `create_device`:

```
[src\main.rs:666] features = PhysicalDeviceFeatures2Builder {
    value: PhysicalDeviceFeatures2 {
        s_type: PHYSICAL_DEVICE_FEATURES_2,
        next: 0x000000c3c42ea888,
        features: PhysicalDeviceFeatures {
            robust_buffer_access: 1,
```

after:
```
[src\main.rs:676] features = PhysicalDeviceFeatures2Builder {
    value: PhysicalDeviceFeatures2 {
        s_type: PHYSICAL_DEVICE_FEATURES_2,
        next: 0x0000000000000000,
        features: PhysicalDeviceFeatures {
            robust_buffer_access: 1,
```

Just checked with 0.19.0 as well to see if it was something that broke after v0.19.0, but broken there as well, unless I'm missing something else.

**Comment by dsvensson** [comment]
#149 is what caused this breakage. Reverting to 0.18.0 prevents pNext = indexingfeatures to be set to NULL.

**Comment by KyleMayes** [comment]
Sorry, I have been neglecting this project recently, I'll take a look at this over the weekend.

**Comment by dsvensson** [comment]
Found this project thanks to your Vulkan tutorial port. When I first stumbled upon the issue I made a small attempt at porting it to ash instead but soon realizing that was a fairly significant uglification of the code base even if most functions and types were named the same. Have you tried working with getting your changes into ash?

**Comment by dsvensson** [comment]
@KyleMayes Any idea what might be the problem given your recent change in that area? Just realized that dynamic rendering builder is only available in latest release, so starting to reach the end of how far 0.18.0 can take me.

**Comment by dsvensson** [comment]
Ported to ash instead.

**Comment by KyleMayes** [comment]
This was happening because `push_next` wasn't handling pushing a pointer chain of structs (`features2` in the code example) onto another pointer chain of structs (`info` in the code example).

`push_next` on the builder for `info` was taking the default `next` value (`NULL`) and making that the new `next` value of the struct being pushed onto `info`.

This mean the `features2` value was having its `next` field set to `NULL` when passed to the `push_next` call for `info`, overwriting its pointer to the `indexing_features` value.

The fix was to iterate over the incoming `next` value and put the old `next` value at the end so that both pointer chains can be merged together rather than the base pointer chain replacing the tail of the incoming pointer chain.
