### ISSUE TITLE
Tutorial: Specifying the number of descriptor sets to allocate

### ISSUE THREAD

**Issue by dariuswiles** [KyleMayes/vulkanalia#205]
The [Descriptor set](https://kylemayes.github.io/vulkanalia/uniform/descriptor_pool_and_sets.html#descriptor-set) section of chapter 27 says (with my **bold** emphasis):

> A descriptor set allocation is described with a `vk::DescriptorSetAllocateInfo` struct. You need to specify the descriptor pool to allocate from, **the number of descriptor sets to allocate**, and the descriptor layout to base them on:
>
> ```rust,noplaypen
> let layouts = vec![data.descriptor_set_layout; data.swapchain_images.len()];
> let info = vk::DescriptorSetAllocateInfo::builder()
>     .descriptor_pool(data.descriptor_pool)
>     .set_layouts(&layouts);
> ```

However, the number of descriptor sets is not specified, at least not explicitly. I couldn't find documentation on how the  `vk::DescriptorSetAllocateInfo` builder functions determine the value for the `descriptor_set_count` field, but looking at the [source code](https://docs.rs/vulkanalia/latest/src/vulkanalia/vk/builders.rs.html#11800-11805), I believe `vk::DescriptorSetAllocateInfoBuilder::set_layouts` sets this field to the length of the array passed. If I'm right, it would be helpful for the text to be modified to explain this. Maybe something like:

"A descriptor set allocation is described with a `vk::DescriptorSetAllocateInfo` struct. You need to specify the descriptor pool to allocate from and the descriptor layout to base them on. The length of the array passed to `set_layouts` determines the number of descriptor sets to allocate."

On a side note, this is a really excellent tutorial and I'm grateful for the time you've spent creating it. Thanks!

**Comment by KyleMayes** [comment]
Thanks for the reports, PRs, and kind words!
