### ISSUE TITLE
Tutorial page on push constants uses slice_from_raw_parts without import

### ISSUE THREAD

**Issue by dariuswiles** [KyleMayes/vulkanalia#219]
A code block on the tutorial page introducing push constants uses the standard `slice_from_raw_parts` function but does not mention needing to change the "use" statement to import it. Specifically, the "main.rs" code changes from:
```use std::ptr::copy_nonoverlapping as memcpy;```
to:
```use std::ptr::{copy_nonoverlapping as memcpy, slice_from_raw_parts};```

It's not hard to figure out from the compiler warning, so it's your choice if you think it worth mentioning in the tutorial.

**Comment by KyleMayes** [comment]
I don't think it's good for there to be any unexpected errors, even they are easy to fix.

I think this used to be imported in an earlier chapter, but things have changed quite a bit recently so I'm not sure.

I'll update this chapter to include this import.

**Comment by dariuswiles** [comment]
Before I opened this issue I looked at the main.rs code for the chapter prior to the push constant chapter, and it does not import `slice_from_raw_parts`. Searching the whole tutorial, I think `slice_from_raw_parts` is first mentioned in the push constant chapter, and it therefore definitely makes sense to introduce this import there.
