### ISSUE TITLE
bytecode module does not exist

### ISSUE THREAD

**Issue by gentlecolts** [KyleMayes/vulkanalia#225]
Was walking through this tutorial, at some point after I had completed the create_shader_module function, the tutorial switched to using the `vulkanalia::bytecode::Bytecode` import.  Minor crisis of going back to this code and wondering where my implementation came from aside, it appears that import does not seem to exist.

my dependencies currently lists `vulkanalia = { version = "=0.22.0", features = ["libloading", "provisional", "window"] }`, which seems to be the latest version available according to `cargo search vulkanalia`.  System is Manjaro Linux.

**Comment by KyleMayes** [comment]
That is quite strange, v0.22.0 should indeed have the `bytecode` module, I've checked the documentation on `docs.rs` and the code from `crates.io` for v0.22.0 and both have the module.

1. If you haven't already, perhaps running `cargo clean` before attempting a recompilation could help
2. If not, what happens if you clone this repository and run one of the tutorial code samples?

Example:
```
cargo run --bin 32_secondary_command_buffers
```

**Comment by gentlecolts** [comment]
Cloning and running the above command appears to work correctly.  I notice, however this project does include vulkanalia as part of its directory, I'm letting it come from crates.io


Cargo.toml:
```
[package]
name = "rust-hello-vulkan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
lazy_static = "1"
log = "0.4"
nalgebra-glm = "0.18"
png = "0.17"
pretty_env_logger = "0.4"
thiserror = "1"
tobj = { version = "3", features = ["log"] }
vulkanalia = { version = "=0.22.0", features = ["libloading", "provisional", "window"] }
winit = "0.28"
```

**Comment by KyleMayes** [comment]
I created a new Cargo project with `cargo new` and replaced the generated `Cargo.toml` with your `Cargo.toml`.

The `vulkanalia::bytecode::Bytecode` import worked fine in the `main.rs` file in the new project with your dependencies.

I don't really know what's going on here.

**Comment by gentlecolts** [comment]
I'm scratching my head a little bit here too actually...I just made a fresh project with that same Cargo.toml, barebones hello world using the import, ::new() constructor, seems to build...

**Comment by gentlecolts** [comment]
Well i guess the mystery will remain myseterious, just ran cargo clean on my project and then built again, this time from the command line, and it ran, intelliJ now seems ok with the code, and running from the gui as i had been before seem to work.  No idea what that could half been but I think it's safe to close this

**Comment by RowDaBoat** [comment]
I can confirm I had the exact same issue and fixed it by just updating the vulkanalia crate from ver 0.21.0 to ver 0.22.0 in my Cargo.toml, then using "load cargo changes" in my RustRover IDE.
