### ISSUE TITLE
Simple example in documentation takes 2.7GB RAM

### ISSUE THREAD

**Issue by ShlomiRex** [KyleMayes/vulkanalia#227]
![image](https://github.com/KyleMayes/vulkanalia/assets/17744127/5872070e-84a3-4938-89a4-09564fc07d3a)

![image](https://github.com/KyleMayes/vulkanalia/assets/17744127/cac7ed8e-bcdc-48d9-ad90-5df6a40ac349)

The documentation: https://kylemayes.github.io/vulkanalia/setup/base_code.html

Base code:

```
#![allow(
dead_code,
unused_variables,
clippy::too_many_arguments,
clippy::unnecessary_wraps
)]

use anyhow::Result;
use winit::dpi::LogicalSize;
use winit::event::{Event, WindowEvent};
use winit::event_loop::{ControlFlow, EventLoop};
use winit::window::{Window, WindowBuilder};

fn main() -> Result<()> {
    pretty_env_logger::init();

    // Window

    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
        .with_title("Vulkan Tutorial (Rust)")
        .with_inner_size(LogicalSize::new(1024, 768))
        .build(&event_loop)?;

    // App

    let mut app = unsafe { App::create(&window)? };
    let mut destroying = false;
    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Poll;
        match event {
            // Render a frame if our Vulkan app is not being destroyed.
            Event::MainEventsCleared if !destroying =>
                unsafe { app.render(&window) }.unwrap(),
            // Destroy our Vulkan app.
            Event::WindowEvent { event: WindowEvent::CloseRequested, .. } => {
                destroying = true;
                *control_flow = ControlFlow::Exit;
                unsafe { app.destroy(); }
            }
            _ => {}
        }
    });
}

/// Our Vulkan app.
#[derive(Clone, Debug)]
struct App {}

impl App {
    /// Creates our Vulkan app.
    unsafe fn create(window: &Window) -> Result<Self> {
        Ok(Self {})
    }

    /// Renders a frame for our Vulkan app.
    unsafe fn render(&mut self, window: &Window) -> Result<()> {
        Ok(())
    }

    /// Destroys our Vulkan app.
    unsafe fn destroy(&mut self) {}
}

/// The Vulkan handles and associated properties used by our Vulkan app.
#[derive(Clone, Debug, Default)]
struct AppData {}
```

Using:

```
vulkanalia = { version = "=0.21.0", features = ["libloading", "provisional", "window"] }
```

This simple examples takes 2.7GB. This is unreasonable.

**Comment by KyleMayes** [comment]
Is the concern here that your IDE is using too much memory when working on a project that uses `vulkanalia`, or that an executable compiled from the `00_base_code.rs` tutorial code uses too much memory?

It looks like actual `rust-test.exe` process is using 1.6 MB in your screenshot, which closely matches the 1.5 MB I get when I run `cargo run --bin 00_base_code` on my machine with or without `--release`.

2.7 GB doesn't seem unreasonable for an IntelliJ product, I don't use IntelliJ for Rust development, but I do use it for Kotlin development. For example, when I open the generator project in this repository with IntelliJ, it uses about 2.1 GB of memory.

**Comment by ShlomiRex** [comment]
> Is the concern here that your IDE is using too much memory when working on a project that uses `vulkanalia`, or that an executable compiled from the `00_base_code.rs` tutorial code uses too much memory?
> 
> It looks like actual `rust_test.exe` process is using 1.6 MB in your screenshot, which closely matches the 1.5 MB I get when I run `cargo run --bin 00_base_code` on my machine with or without `--release`.
> 
> 2.7 GB doesn't seem unreasonable for an IntelliJ product, I don't use IntelliJ for Rust development, but I do use it for Kotlin development. For example, when I open the generator project in this repository with IntelliJ, it uses about 2.1 GB of memory.

Thanks for clarifications.
I ran from the terminal and indeed it takes 0.8MB.
