### ISSUE TITLE
update the ebook tutorial

### ISSUE THREAD

**Issue by Mon-ius** [KyleMayes/vulkanalia#242]
For last version of winit, for example, the API has been changed, see https://github.com/rust-windowing/winit/blob/master/examples/window.rs

However, the code from https://kylemayes.github.io/vulkanalia/setup/base_code.html was not updated to follow up.

**Comment by KyleMayes** [comment]
Updated thanks to https://github.com/KyleMayes/vulkanalia/pull/244.

**Comment by Mon-ius** [comment]
@KyleMayes cool~
