### ISSUE TITLE
Querying required instance extensions always fails

### ISSUE THREAD

**Issue by cking** [KyleMayes/vulkanalia#25]
When i try to use vulkanalia's `get_required_instance_extensions` i always get an empty list.

The memory view during debug looks like:
![image](https://user-images.githubusercontent.com/196108/109361331-0d10f580-7889-11eb-86b8-e61890bc4aa7.png)

If i copy the function and change `.collect::<HashSet<_>>()` to `.collect::<Vec<_>>()` it works.

I am using cargo/rustc version 1.49.0 stable on win32 (MSVC).
Does that help?

**Comment by cking** [comment]
also the comparison between the c_char arrays seem to not work.

**Comment by KyleMayes** [comment]
I compiled and ran the triangle example with Rust `1.49.0-i686-pc-windows-msvc` and `1.49.0-x86_64-pc-windows-msvc` and in both cases `get_required_instance_extensions` returned the correct list of extensions.

I loosely based the `window` module off of `ash`'s `ash-window` crate, and it seems they have changed their implementation to simply [return the extensions for the raw window handle](https://github.com/MaikKlein/ash/blob/dd2849450fca7a6361fa51883bda7a37daf2add5/ash-window/src/lib.rs#L135). I think I will change my `window` module to do the same which will hopefully also fix this issue.

**Comment by cking** [comment]
I just checked out the current version from git, no changes.
This is my result:

```
vulkanalia\examples>cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `C:\Users\ChristopherKoenig\PrivateProjects\vulkanalia\target\debug\triangle.exe`
thread 'main' panicked at 'could not load vkCreateWin32SurfaceKHR', vulkanalia\src\vk\commands.rs:6830:25
stack backtrace:
   0: std::panicking::begin_panic<str*>
             at C:\Users\ChristopherKoenig\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:521
   1: vulkanalia::vk::commands::{{impl}}::load::fallback
             at C:\Users\ChristopherKoenig\PrivateProjects\vulkanalia\vulkanalia\src\vk\commands.rs:6830
   2: vulkanalia::vk::extensions::KhrWin32SurfaceExtension::create_win32_surface_khr<vulkanalia::Instance>
             at C:\Users\ChristopherKoenig\PrivateProjects\vulkanalia\vulkanalia\src\vk\extensions.rs:6267
   3: vulkanalia::window::create_surface
             at C:\Users\ChristopherKoenig\PrivateProjects\vulkanalia\vulkanalia\src\window.rs:56
   4: examples::App::new<triangle::TriangleExample>
             at .\src\lib.rs:78
   5: triangle::main
             at .\src\bin\triangle.rs:23
   6: core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, anyhow::Error>,tuple<>>
             at C:\Users\ChristopherKoenig\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\Users\ChristopherKoenig\PrivateProjects\vulkanalia\target\debug\triangle.exe` (exit code: 101)
```

**Comment by KyleMayes** [comment]
Well that's because I hadn't made the change yet!

However, the proposed change is now in the `misc-updates` branch if you want to try it out.

I also need to make some other changes which will be in the next release, namely that I think I need to mark pretty much all the functions as `unsafe` due to how easy it is to run into undefined behavior/crashes/etc. in Vulkan even with the tiniest of mistakes.

**Comment by cking** [comment]
> Well that's because I hadn't made the change yet!

Just wanted to make sure that I have the issues with the provided example as well :) (a verification so to say)


> I also need to make some other changes which will be in the next release, namely that I think I need to mark pretty much all the functions as `unsafe` due to how easy it is to run into undefined behavior/crashes/etc. in Vulkan even with the tiniest of mistakes.

I was happy i didnt have to do much unsafe (unlike ash) but i can see and understand your point.

**Comment by KyleMayes** [comment]
Sorry, I read it as you thought I meant that I had pushed a fix.
Fortunately, now I have (maybe).

The updated `window` module is in `v0.6.0` which has just now been released, hopefully it fixes the window extension problem.
Unfortunately so is The Great Unsafening™️.

I agree having everything marked as unsafe is annoying but I shot myself in the foot many times while porting/writing the tutorial chapters (which included several segfaults and mysterious crashes). I can't in good conscience let these functions stay bereft of `unsafe`, our benevolent crab overlord Ferris would surely disapprove.

**Comment by cking** [comment]
just a heads up, latest version (0.6) works as expected.

![image](https://user-images.githubusercontent.com/196108/109386084-9a3f6300-78f8-11eb-9da8-87bd00f1b62d.png)
