### ISSUE TITLE
Segmentation fault when passing a temporary value to builders

### ISSUE THREAD

**Issue by guimauveb** [KyleMayes/vulkanalia#260]
Hello,

I noticed a different behavior in debug and release mode on some builder methods.

When allocating descriptor sets for instance. If I pass a temporary reference to the descriptor set layouts to the builder, like so:
```rust
    let info = vk::DescriptorSetAllocateInfo::builder()
        .descriptor_pool(self.descriptor_pool)
        .set_layouts(&[self.descriptor_set_layouts[0]])
        .build();
    unsafe { self.device.allocate_descriptor_sets(&info)?[0] }
```

the program compiles and runs fine in `debug` mode, but it triggers a validation error and generates a segmentation fault in `release` mode.

```bash
ERROR vulkan_engine         > (VALIDATION) Validation Error: [ VUID-VkDescriptorSetAllocateInfo-pSetLayouts-parameter ] Object 0: handle = 0x590e69f3f990, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xc855ce8 | vkAllocateDescriptorSets(): pAllocateInfo->pSetLayouts[0] Invalid VkDescriptorSetLayout Object 0x82f1b4bfea06b07c. The Vulkan spec states: pSetLayouts must be a valid pointer to an array of descriptorSetCount valid VkDescriptorSetLayout handles (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkDescriptorSetAllocateInfo-pSetLayouts-parameter)
[2]    360867 segmentation fault (core dumped)  cargo r --release
```

If I create a reference to the set layouts via a `let` binding, the issue is gone in `release` mode (and still works fine in `debug` mode).

```rust
    let set_layouts = &[self.descriptor_set_layouts[0]];
    let info = vk::DescriptorSetAllocateInfo::builder()
        .descriptor_pool(self.descriptor_pool)
        .set_layouts(set_layouts)
        .build();
    unsafe { self.device.allocate_descriptor_sets(&info)?[0] }
```

The segmentation fault arises when calling `allocate_descriptor_sets`, not when creating the info structure.

I looked at [the code](https://docs.rs/vulkanalia/latest/src/vulkanalia/vk/builders.rs.html#12442) and it seems that the lifetime of the reference is not tied to the final value returned by the `built` method, which is why the compiler does not complain. 

I don't know how this issue could be fixed. Should the lifetime of the reference to the set layouts be tied to the value returned by `build`?

I noticed the exact same issue with `vk::WriteDescriptorSet::builder()` and the `image_info` parameter:
```rust
    let image_info = vk::DescriptorImageInfo::builder()
        .image_view(texture_image_view)
        .image_layout(vk::ImageLayout::SHADER_READ_ONLY_OPTIMAL)
        .sampler(self.sampler)
        .build();
    let dsc_writes = [vk::WriteDescriptorSet::builder()
        .dst_set(dsc_set)
        .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
        .dst_array_element(0)
        .dst_binding(0)
        .image_info(&[image_info])
        .build()];
```

When calling
```rust
    unsafe {
        self.device
            .update_descriptor_sets(&dsc_writes, &[] as &[vk::CopyDescriptorSet]);
    }
```

it triggers a validation error and a segmentation fault:

```bash
 ERROR vulkan_engine         > (VALIDATION) Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-02996 ] Object 0: handle = 0x56d54df7b990, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x1cc3d039 | vkUpdateDescriptorSets(): pDescriptorWrites[0].pImageInfo[0].imageView Invalid VkImageView Object 0x2. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, or VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, the imageView member of each element of pImageInfo must be either a valid VkImageView handle or VK_NULL_HANDLE (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-02996)
```

Some details about my configuration:

```
CPU: AMD Ryzen 9 5900X 
GPU: NVIDIA GeForce RTX 4090 
OS: Arch Linux x86_64 (kernel: 6.8.2-arch2-1)
Desktop: GNOME 46.0 on Wayland
Rust 1.74.1
```

Thank you for your work, I really like the fact that there is almost no abstraction layer between Vulkan and the Rust wrapper. It's been working great so far!

**Comment by KyleMayes** [comment]
I've added a link to the API Concepts sub-chapter to the `vulkanalia` crate-level documentation as well as a new "Quick Tips" section (initially just with the one tip to avoid calling `build` on builder structs when you can):

https://github.com/KyleMayes/vulkanalia/blob/fe39f06828b4131d37308deb052c80d953c499ac/vulkanalia/src/lib.rs#L13-L15
