### ISSUE TITLE
License

### ISSUE THREAD

**Issue by peterc-s** [KyleMayes/vulkanalia#264]
Was just crediting the work here in my own project and noticed your [LICENSE.txt](https://github.com/KyleMayes/vulkanalia/blob/master/LICENSE.txt) isn't properly filled out with year and name.

**Comment by KyleMayes** [comment]
That's the template for the notice block that you're recommended to add to every source file, but  my understanding is that it isn't strictly necessary from a legal standpoint.

I'm using [SPDX license identifiers](https://spdx.org/licenses/) in my source files as a more succinct alternative, e.g.:
```
// SPDX-License-Identifier: Apache-2.0
```
