### ISSUE TITLE
Chapter 7 - Validation Layer

### ISSUE THREAD

**Issue by KaaPex** [KyleMayes/vulkanalia#273]
Hi.
I'm wandering, why are you using `create_debug_utils_messenger_ext` and `destroy_debug_utils_messenger_ext` methods with `info.push_next(&mut debug_info)`?
 What the purpose in this case, is it not enough just use `info.push_next(&mut debug_info)`?

**Comment by KyleMayes** [comment]
https://github.com/KyleMayes/vulkanalia/blob/b7a91d422ac477ffbde0238f87107c885f809fad/tutorial/src/02_validation_layers.rs#L179-L189

It does seem redundant, but they serve different purposes.
(I can't find any Vulkan documentation that explains this, but this is what I've learned through experimentation)

Adding the debug messenger info as an extension struct to the `vk::InstanceCreateInfo` sets up debug logging to work for the instance and only the instance, not devices created with the instance.

We need to call `vkCreateDebugUtilsMessengerEXT` to set up debug logging to work for devices created with the instance.

You can observe this difference by using the code from one of the later chapters (e.g., `32_secondary_command_buffers`) and commenting out either of the lines equivalent to 180 or 188 in the above code. When I commented out the `vkCreateDebugUtilsMessengerEXT` call on my machine there were a few fewer debug logs from Vulkan (seemingly device-specific ones like `Inserted device layer "VK_LAYER_KHRONOS_validation"`).

I should mention this in the tutorial, maybe I can find a place in the Vulkan documentation that better explains this to link to.

**Comment by pcasotti** [comment]
I believe this is the relevant documentation:

> To capture events that occur while creating or destroying an instance, an application can link a [VkDebugReportCallbackCreateInfoEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap50.html#VkDebugReportCallbackCreateInfoEXT) structure or a [VkDebugUtilsMessengerCreateInfoEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap50.html#VkDebugUtilsMessengerCreateInfoEXT) structure to the pNext element of the VkInstanceCreateInfo structure given to vkCreateInstance. This callback is only valid for the duration of the [vkCreateInstance](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap4.html#vkCreateInstance) and the [vkDestroyInstance](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap4.html#vkDestroyInstance) call. Use [vkCreateDebugReportCallbackEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap50.html#vkCreateDebugReportCallbackEXT) or [vkCreateDebugUtilsMessengerEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap50.html#vkCreateDebugUtilsMessengerEXT) to create persistent callback objects.

from [here](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap4.html#initialization-instances), under `VkInstanceCreateInfo`.

**Comment by KyleMayes** [comment]
Thanks for finding the relevant documentation.
I've added a note to this chapter explaining the seeming redundancy and linking to that part of the spec.
