### ISSUE TITLE
Acceleration structure bit fields

### ISSUE THREAD

**Issue by InBetweenNames** [KyleMayes/vulkanalia#73]
I noticed that Vulkanalia's acceleration structures reference seems to ignore bitfield sizes:

https://docs.rs/vulkanalia-sys/0.12.0/vulkanalia_sys/struct.AccelerationStructureInstanceKHR.html

If you look at the actual Vulkan spec, they are present:

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccelerationStructureInstanceKHR.html

The note at the bottom is helpful to understand the intent behind the structure description.

I haven't tested out acceleration structures with Vulkanalia yet, but I haven't found any code in this library that performs the bitfield mapping.  Ash takes this approach to handle this case:

https://github.com/MaikKlein/ash/blob/0cddbad6185231445c7cc7cc42a0d41b42dd63cd/ash/src/vk/prelude.rs#L12

Does Vulkanalia properly handle bitfields for these kinds of structures in Vulkan?  Or is this perhaps a bug?

**Comment by KyleMayes** [comment]
It's a bug. I didn't notice the bitfields when I was writing the code generator since they are so rare and don't appear in any commonly used structures. I'll address this after I figure out why the automatic updates are failing.

**Comment by KyleMayes** [comment]
Fixed bitfield support is published in `v0.13.0`.

**Comment by InBetweenNames** [comment]
That was fast!  Thanks!
