### ISSUE TITLE
06_swapchain_creation.rs image count sanity check wrong

### ISSUE THREAD

**Issue by str0yd** [KyleMayes/vulkanalia#77]
in https://github.com/KyleMayes/vulkanalia/blob/master/tutorial/src/06_swapchain_creation.rs you set the image count to `min_image_count + 1` and then do a sanity check:
```
let mut image_count = support.capabilities.min_image_count + 1;
if support.capabilities.max_image_count != 0
    && image_count > support.capabilities.min_image_count
{
    image_count = support.capabilities.max_image_count;
}
```
I think it sould be `&& image_count > support.capabilities.max_image_count`

**Comment by KyleMayes** [comment]
Good catch, I'll update this.
