### ISSUE TITLE
physical_devices_and_queue_families.md check_physical_device error

### ISSUE THREAD

**Issue by attecon** [KyleMayes/vulkanalia#79]
Hello, I'm working through the tutorial and within https://github.com/KyleMayes/vulkanalia/blob/master/tutorial/book/src/setup/physical_devices_and_queue_families.md it looks like the function body code for `pick_physical_device` is instead placed inside `check_physical_device` at the bottom of this tutorial page.

**Comment by CaesarXInsanium** [comment]
i also thought that it was weird.

**Comment by KyleMayes** [comment]
Good catch, looks like I got my function declarations mixed up. That code
should be in `pick_physical_device` like it is in the full code.

I'll publish an update later when I get a chance.

**Comment by CaesarXInsanium** [comment]
Good job in this project. It is coming along well.
